apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-exporter
  namespace: default
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: controller # Matches service selector
      app.kubernetes.io/instance: nginx-ingress
      app.kubernetes.io/name: ingress-nginx
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
