apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-02-11T20:32:09Z"
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: nginx
  name: nginx
  namespace: default
  resourceVersion: "2975"
  uid: 4bb16cc9-30e1-420f-b4de-986b9e366797
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.226.197
  clusterIPs:
    - 172.20.226.197
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 32580
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - hostname: a4bb16cc930e1420fb4de986b9e36679-369917909.eu-west-2.elb.amazonaws.com
