apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-loki-access
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: grafana
    namespace: monitoring
roleRef:
  kind: Role
  name: loki-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loki-access
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
