name: Build and Push to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 207567758913.dkr.ecr.eu-west-2.amazonaws.com

      - name: Build Docker Image
        run: docker build -t nginx .

      - name: Tag Image for AWS ECR
        run: docker tag nginx:latest 207567758913.dkr.ecr.eu-west-2.amazonaws.com/nginx:latest

      - name: Push Image to AWS ECR
        run: docker push 207567758913.dkr.ecr.eu-west-2.amazonaws.com/nginx:latest
