name: Build and Push to AWS ECR #Names the GitHub Actions workflow as "Build and Push to AWS ECR"
on: #Defines the events that trigger the workflow
  push: #Triggers on push events
    branches: #Specifies the branches to monitor
      - main #Runs the workflow when code is pushed to the "main" branch

jobs: #Defines the jobs to execute in the workflow
  build: #Names the job "build"
    name: Build and Push Docker Image #Labels the job as "Build and Push Docker Image" in the GitHub UI
    runs-on: ubuntu-latest #Runs the job on the latest Ubuntu virtual machine

    steps: #Lists the sequential steps to perform in the job
      - name: Checkout repository #Checks out the repository code
        uses: actions/checkout@v4 #Uses the checkout action (version 4) to fetch the repo

      - name: Configure AWS credentials #Configures AWS authentication for ECR access
        uses: aws-actions/configure-aws-credentials@v2 #Uses the AWS credentials action (version 2)
        with: #Passes AWS credential parameters
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} #Uses a GitHub secret for AWS access key
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} #Uses a GitHub secret for AWS secret key
          aws-region: eu-west-2 #Sets the AWS region to eu-west-2 (London)

      - name: Login to AWS ECR #Authenticates Docker with AWS ECR
        run: | #Runs a shell command
          aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 207567758913.dkr.ecr.eu-west-2.amazonaws.com  #Gets ECR login password and logs into your ECR repository (account ID: 207567758913)

      - name: Build Docker Image #Builds the Docker image from the Dockerfile
        run: docker build -t nginx . #Runs "docker build" to create an image named "nginx" from the current directory

      - name: Tag Image for AWS ECR #Tags the Docker image for ECR
        run: docker tag nginx:latest 207567758913.dkr.ecr.eu-west-2.amazonaws.com/nginx:latest #Tags the "nginx" image with your ECR repository URI

      - name: Push Image to AWS ECR #Pushes the Docker image to ECR
        run: docker push 207567758913.dkr.ecr.eu-west-2.amazonaws.com/nginx:latest #Uploads the tagged image to your ECR repository
